### PR TITLE
Refactor image loading

### PR DESCRIPTION
**Pull request by eraychumak**
All images across Dim _should_ now:
- [x] Swap smoothly between sources _(if an animation is given ofc, by default simple opacity change)_
- [x] Retry to fetch again every 5 seconds 3 times if failed to load - only per window session _(to not spam)_
- [x] Cancel fetch if user navigates away.

Other changes
- Fixes libraries section in sidebar not showing when adding new library for the first time
- Theme and favicon should now work even if server is offline because they were housed under the WS component
- Tweaks to banner colors

### CODE REVIEW

**Comment by vgarleanu** [comment]
image
Media page banners dont fill the entire media page now.

**Comment by vgarleanu** [comment]
image
Posters that 404 should be replcaed with the logo of dim.

**Comment by eraychumak** [comment]
> 
> 
> image
> Media page banners dont fill the entire media page now.

This was an intentional decision, trialing it out to see if maybe it's best to show the banner fully rather than sacrificing both top and bottom parts just to have it full width. Especially if it's a wide screen, this choice makes it a bit more I guess 'practical' instead of it being a "strip". Definitely need to play with the layout more tho idk, thoughts?

**Comment by eraychumak** [comment]
> 
> 
> image
> Posters that 404 should be replcaed with the logo of dim.

Can't seem to re-create this...tried clearing `metadata` folder too...pushed a commit just now, see if it fixed that.

**Comment by vgarleanu** [comment]
> > image
> > Posters that 404 should be replcaed with the logo of dim.
> 
> Can't seem to re-create this...tried clearing `metadata` folder too...pushed a commit just now, see if it fixed that.

Nope, didnt work. Nothing changed, it shows the same thing.

> > image
> > Media page banners dont fill the entire media page now.
> 
> This was an intentional decision, trialing it out to see if maybe it's best to show the banner fully rather than sacrificing both top and bottom parts just to have it full width. Especially if it's a wide screen, this choice makes it a bit more I guess 'practical' instead of it being a "strip". Definitely need to play with the layout more tho idk, thoughts?

Lets revert it back to the way it was for now, once we get more content into the media page we can think about layout and content optimization more. Right now we just need to make stuff fill in the space.

**Comment by eraychumak** [comment]
> 
> 
> image
> Posters that 404 should be replcaed with the logo of dim.

Should be fixed now.

**Pull request merged**
