### PR TITLE
feat: use JASSUB for ASS rendering

### PR DESCRIPTION
**Pull request by ThaUnknown**
This PR migrates from JSO to JASSUB for ASS subtitle rendering.

The list of improvements is long, from better resize handling, to handling variable resolution video, handling variable framerate video, framerate bound rendering, support for local fonts, support for video color spaces, faster rendering, smaller filesizes, supporting anamorphic video and a lot of others.

This repo used an outdated version of react scripts, which had an outdated version of babel loader that didn't support some new JS syntax, which errored on build. I had to update the reacts scripts package.

I didn't have time to test this on actual video playback, but it compiles and loads correctly, and doesn't cause any runtime errors.

### CODE REVIEW

**Comment by mental32** [comment]
@ThaUnknown this looks awesome! but we need to remove that .wasm file and not check it in. if we can generate it with a script that would be pretty cool.

**Comment by vgarleanu** [comment]
> @ThaUnknown this looks awesome! but we need to remove that .wasm file and not check it in. if we can generate it with a script that would be pretty cool.

Generating it with a script will make our compilation process expensive. Best we check it in. Maybe we could use git lfs?


On a sidenote, @ThaUnknown is there any way to stream ASS subtitles into your fork as opposed to supplying a complete ASS file?

**Comment by mental32** [comment]
we cant pivot out of a bad history we can always pivot into moving a script that generates artefacts to git-lfs either way whatever is easiest just not checking it in.

**Comment by ThaUnknown** [comment]
this is a tech debt you created by using react-scripts instead of simply writing a 20LOC webpack config

**Comment by ThaUnknown** [comment]
also generating that wasm file, takes roughly 20-30 minutes, because its C you need to compile, I assume you mean import it from the library?

**Comment by ThaUnknown** [comment]
@mental32 I removed the manually copied files, they are now imported during build from the dependency directly [the correct way of doing it]

@vgarleanu "yes" it can do that, but it's more like it allows you to manually create and remove "events" aka subtitles, I use this myself in combination with an EBML parser to append new events as they are parsed from an incoming video, so if by streaming you mean "just add new events" then yeah, but if you mean "swap events for currently active ones" then it provides the framework for you to implement it yourself via createEvent, setEvent and removeEvent

**Pull request merged**
