### PR TITLE
Add feature system_ff

### PR DESCRIPTION
**Pull request by eatradish**
This feature will look for ffmpeg and ffprobe on the system, and will report an error if they are not present, which is necessary for distribution software maintenance, use `--features system_ff` to turn on this feature

### CODE REVIEW

**Comment by vgarleanu** [comment]
I think it might be better if this was not a feature flag and was instead an argument we could pass to the dim binary.

**Comment by eatradish** [comment]
> I think it might be better if this was not a feature flag and was instead an argument we could pass to the dim binary.



> I think it might be better if this was not a feature flag and was instead an argument we could pass to the dim binary.

Should I look for `utils/ffmpeg` and `utils/ffprobe` to exist when the program cannot find them in the `PATH`?

like:
```
which("ffmpeg").unwrap_or("utils/ffmpeg)
```

**Comment by vgarleanu** [comment]
> > I think it might be better if this was not a feature flag and was instead an argument we could pass to the dim binary.
> 
> Should I look for `utils/ffmpeg` and `utils/ffprobe` to exist when the program cannot find them in the `PATH`?
> 
> like:
> 
> ```
> which("ffmpeg").unwrap_or("utils/ffmpeg")
> ```

Yes but only when the user has turned on the `--use-system-ffmpeg` arg, otherwise if we cant find `utils/ffmpeg` we should abort at launch.

**Comment by eatradish** [comment]
> > > I think it might be better if this was not a feature flag and was instead an argument we could pass to the dim binary.
> > 
> > 
> > Should I look for `utils/ffmpeg` and `utils/ffprobe` to exist when the program cannot find them in the `PATH`?
> > like:
> > ```
> > which("ffmpeg").unwrap_or("utils/ffmpeg")
> > ```
> 
> Yes but only when the user has turned on the `--use-system-ffmpeg` arg, otherwise if we cant find `utils/ffmpeg` we should abort at launch.

I made some changes and now it works, but the code will look ugly due to the limitation of lazy_static, as well as one place with if let hell, I wonder what I should do?

**Comment by mental32** [comment]
@eatradish sorry for the delay. this looks good but the PR has gone stale. if you would like to author this could you rebase the branch so that it is up to date and the changes work?

**Pull request closed without merging**
