### PR TITLE
Fixed template docker-compose file

### PR DESCRIPTION
**Pull request by nooobcoder**
Please **review the changelog** for `docker-compose-template.yml` and merge the changes.
The image name and the branch was incorrect in the main commit. Fixed it and tested it locally, works like a charm.
The future of **dim** looks very promising and the attention it got, just simple UI and no bloat, comes with support for Docker, absolutely like the development.

Keep up the good work ✨💖

By, @nooobcoder

Thank you.
@Dusk-Labs

### CODE REVIEW

**Comment by nooobcoder** [comment]
@dessalines Hi, can you review this PR of mine, please.

**Review by dessalines — APPROVED** [review]
Looks good to me.

**Comment by vgarleanu** [comment]
Happy to merge this although I think we will have to revert this change once we get a new stable release.

**Comment by nooobcoder** [comment]
Thanks for the merge @vgarleanu

**Pull request merged**
