### PR TITLE
Format, lint, and type check on commit and in CI.

### PR DESCRIPTION
**Pull request by jimmycuadra**
This PR adds formatting with Prettier and linting with ESLint to the React build in CI, as well as a Git pre-commit hook to run these processes (and TypeScript type checking) on files being committed using Husky and lint-staged. The goal is to ensure consistent formatting regardless of which developer works on the code and to keep code problems from reaching the main branch.

I modified the existing `.eslintrc` file to remove rules related to layout and formatting which are now handled by Prettier. On commit, any files that are being staged for commit will be formatted with Prettier automatically and will have ESLint violations fixed automatically, where possible. Anything not automatically fixable will cause the commit to fail and list the problems the developer must fix manually.

The bulk of the code in `ui/lint-staged.config.js` is used to prevent lint-staged from attempting to run ESLint on files that it explicitly ignores, because that will result in a lint warning, which will fail the `eslint` run, in turn. See https://github.com/eslint/eslint/issues/15010 for details on that issue. The code for ignoring files comes from lint-staged's documentation: https://github.com/okonet/lint-staged/blob/f9f65380dc3fc6aaa5627abe92f4e26d5b7a25de/README.md#how-can-i-ignore-files-from-eslintignore

There was one ESLint warning in `ui/src/Modals/SelectMediaFile/Activators/Episode.jsx` that I had to fix as well. The rule was "react-hooks/exhaustive-deps" in relation to the use of `epRef.current` in the `useEffect` return value.

The second commit formats all existing front end source code with Prettier so that the React build can pass. It'll be easier to review the meaningful changes here by looking at just the first commit.

### CODE REVIEW

**Comment by vgarleanu** [comment]
We might also want to include a git hook that makes sure code is properly formatted before pushing.

**Comment by jimmycuadra** [comment]
> We might also want to include a git hook that makes sure code is properly formatted before pushing.

It does! 😃 The lint-staged hook will automatically format any files being staged for commit.

**Comment by vgarleanu** [comment]
> > We might also want to include a git hook that makes sure code is properly formatted before pushing.
> 
> It does! 😃 The lint-staged hook will automatically format any files being staged for commit.

Ah right, I just saw the .husky file, I initially assumed that was separate from .git hooks. Is using husky necessary? Wouldn't that mean Devs will have to pull in an extra dependency even tho git comes with hooks support by default?

**Comment by jimmycuadra** [comment]
Husky is what automates the installation of the Git hook. If you look at the "scripts" section of package.json, you'll see a new "prepare" script. This is an npm/yarn hook that automatically executes when installing dependencies. So when someone works on the front end code, the hook will be installed without them having to even know about it. As far as I understand, Husky is the de facto tool for doing this in React projects.

**Pull request merged**
