### PR TITLE
improvements on the Search Engine. 

### PR DESCRIPTION
**Pull request by jeanzless**
before this PR was made, whenever an user were to click on a genre in the library there would appear an error in which no media files would show. this is because the search engine would only work for titles but did not support genres. 

after this PR I've fixed that problem and now it allows you to:

-The search engine also allows queries on genres as well.
-when you press a Movie/Series and you press on the genre of said media file, it will allows you to search that genre and find all of the media files that have the same genre.

### CODE REVIEW

**Comment by vgarleanu** [comment]
Looks good, does this work on `year`?

**Comment by rodrimarchese** [comment]
Only a suggestion:

Do we want the word we are looking for be between single quotes? e.x.:  'word' 


image
image
image



Maybe double quotes are nicer..


image
image
image






Or none of them:

image
image
image


appart from this, works fine!

**Review by rodrimarchese — APPROVED** [review]

**Comment by vgarleanu** [comment]
Lets just keep the header to ex. "Query results for genre Action"

**Comment by rodrimarchese** [comment]
Only left the double quotes for the user manual search, like searching for a title:
image

Remove quotes for genre and year

**Comment by vgarleanu** [comment]
Can we run prettier on this branch? The react ci pipeline is failing. cc: @rodrimarchese

**Pull request merged**
